- doc/client_design.md
Fix https://github.com/PaddlePaddle/cloud/issues/16
> Add client desgin

- paddlecloud/paddlecloud/settings.py
- paddlecloud/paddlecloud/urls.py
- paddlecloud/paddlejob/__init__.py
- paddlecloud/paddlejob/cephfs_volume.py
- paddlecloud/paddlejob/paddle_job.py
- paddlecloud/paddlejob/tests/test_cephfs_volume.py
- paddlecloud/paddlejob/tests/test_paddle_job.py
- paddlecloud/paddlejob/utils.py
- paddlecloud/paddlejob/views.py
> Add submit job api

- paddlecloud/notebook/views.py
- paddlecloud/paddlecloud/settings.py
- paddlecloud/paddlejob/paddle_job.py
- paddlecloud/paddlejob/views.py
- paddlecloud/paddlejob/volume.py
> Secret registry

- doc/usage_cn.md
- docker/paddle_k8s
- paddlecloud/paddlejob/paddle_job.py
- paddlecloud/paddlejob/views.py
> Support submit v2 API job

- doc/client_design.md
- doc/usage_cn.md
- go/paddlecloud/config.go
- paddlecloud/paddlejob/views.py
> update paddle configure

- paddlecloud/paddlecloud/settings.py
- paddlecloud/paddlejob/views.py
> Fix k8s client

- doc/usage_cn.md
> Doc: how to prepare the cloud dataset

- go/paddlecloud/logs.go
Fix https://github.com/PaddlePaddle/cloud/issues/145
> Fix log command error

- paddlecloud/notebook/views.py
> Fix conflit secret error

- .tools/gen_config.sh
- .travis.yml
- go/filemanager/pfsmodules/chunkmeta_test.go
- go/filemanager/pfsmodules/command.go
- go/filemanager/pfsmodules/cp_test.go
- go/filemanager/pfsmodules/ls_test.go
Fix https://github.com/PaddlePaddle/cloud/issues/156
Add test case of `ls` `chunkmeta` `cp`.
> add testcase

- paddlecloud/paddlejob/views.py
Fix https://github.com/PaddlePaddle/cloud/issues/178
> fix ls path validation

- doc/tutorial_cn.md
- doc/usage_cn.md
Fix https://github.com/PaddlePaddle/cloud/issues/180
Fix https://github.com/PaddlePaddle/cloud/issues/2
> Tutorial and usage update

- docker/paddle_k8s
- go/paddlecloud/get.go
- paddlecloud/paddlecloud/urls.py
- paddlecloud/paddlejob/views.py
Fix https://github.com/PaddlePaddle/cloud/issues/195
Note here's still a problem when train exited with error, submit with:
```
-entry "sleep 30 && exit 136"
```
will not show message when `paddlecloud get workers [jobname]`
> Prettify output

- go/paddlecloud/simplefile.go
- go/paddlecloud/submit.go
> Upload files with recursion

- .gitignore
- .pre-commit-config.yaml
- .tools/check_style.sh
- .travis.yml
- go/cmd/pfsserver/main.go
- go/filemanager/pfsmodules/chunkmeta.go
- go/filemanager/pfsmodules/chunkmeta_test.go
- go/filemanager/pfsmodules/touch.go
- go/filemanager/pfsserver/handler.go
- go/filemanager/pfsserver/routes.go
- go/glide.lock
- go/glide.yaml
- go/paddlecloud/registry.go
- go/utils/pathutil/pathutil.go
According https://github.com/PaddlePaddle/Paddle/pull/2643
> Add cloud pre-commit.

- doc/usage_cn.md
- go/paddlecloud/simplefile.go
- go/paddlecloud/submit.go
> Fix invalid job path

- docker/k8s_tools.py
- docker/paddle_k8s
- go/paddlecloud/submit.go
- paddlecloud/paddlecloud/settings.py
- paddlecloud/paddlejob/paddle_job.py
- paddlecloud/paddlejob/views.py
Fix https://github.com/PaddlePaddle/cloud/issues/213
> [Done]Fault tolerant job

- .travis.yml
- k8s/cloud_deployment.yaml
- k8s/mysql_deployment.yaml
- k8s/mysql_service.yaml
- paddlecloud/notebook/templates/notebook.html
- paddlecloud/notebook/utils.py
- paddlecloud/paddlecloud/travis_settings.py
Fix https://github.com/PaddlePaddle/cloud/issues/222
Run mysql and paddlecloud in different pods.
Fix https://github.com/PaddlePaddle/cloud/issues/224
> Fix notebook errors

- doc/tutorial_cn.md
- doc/usage_cn.md
> add recordio doc

- README.md
- k8s/prepare_dataset.yaml
> Prepare cloud dataset

- demo/word2vec/train.py
Related: https://github.com/PaddlePaddle/cloud/issues/147
> Add w2v demo

- demo/recognize_digits/train.py
> Add demo of recognize_digits on paddlecloud

- demo/understand_sentiment/train.py
> Add demo of understand_sentiment on paddlecloud

- .gitignore
- demo/recommender_system/train_ft.py
Depends on the framework change in https://github.com/PaddlePaddle/cloud/pull/278
> Add recommender system demo fault tolerant mode

- paddlecloud/paddlejob/views.py
> Fix invalid job path with hostPath mode

- demo/fit_a_line/train.py
- demo/label_semantic_roles/train.py
- demo/machine_translation/train.py
- demo/recommender_system/train.py
Related: https://github.com/PaddlePaddle/cloud/issues/147
> Add 4 non-fault-tolerant demos

- doc/client_design.md
> command-line interface redesign 

- go/paddlecloud/get.go
Fix https://github.com/PaddlePaddle/cloud/issues/360
Fix client get terminating pods backward compatibility.
> Fix client compability

- doc/tutorial_cn.md
> download latest command-line file

- paddlecloud/paddlecloud/settings.py
Site of notebook should be same as cloud server's by default. Otherwise, the cloud server cannot access notebook with ingress.
> site of notebook should be same as cloud server's by default

- demo/recognize_digits/train_ft.py
- demo/understand_sentiment/train_ft.py
> Run recognize_digits and understand_sentiment demo with fault tolerant mode.

- demo/fit_a_line/train_ft.py
fixing #409 
with original fc config, the default learning rate will lead to gradient explosion. fixed by adding learning_rate=1e-3
> fix demo fit_a_line

- doc/autoscale_experiment.md
> auto-scale experiment plan

- .gitignore
- doc/autoscale/experiment/autoscale_experiment.md
- doc/autoscale/experiment/python/collector.py
- doc/autoscale/experiment/python/main.py
- doc/autoscale/experiment/python/ploter.py
- doc/autoscale/experiment/python/settings.py
- doc/autoscale/experiment/python/utils.py
> Collect time series data

- doc/autoscale/experiment/.gitignore
- doc/autoscale/experiment/README.md
- doc/autoscale/experiment/control_case1.sh
- doc/autoscale/experiment/k8s/trainingjob.yaml.tmpl
- doc/autoscale/experiment/mnist/train.py
- doc/autoscale/experiment/mnist/train_ft.py
- doc/autoscale/experiment/python/collector.py
- doc/autoscale/experiment/python/main.py
- doc/autoscale/experiment/python/settings.py
- doc/autoscale/experiment/python/utils.py
- docker/paddle_k8s
> Experiment scripts

- go/autoscaler/autoscaler.go
- go/autoscaler/autoscaler_internal_test.go
- go/cmd/controller/controller.go
- go/controller/cluster.go
> Fix scale up with no assigned node

- doc/autoscale/example/convert.py
Fix https://github.com/PaddlePaddle/cloud/issues/460
> Add mkdir_p function

- go/cmd/paddlectl/main.go
- go/controller/autoscaler.go
- go/controller/controller.go
- go/controller/jobparser.go
- go/paddlectl/simplefile.go
- go/paddlectl/submit.go
Fix https://github.com/PaddlePaddle/cloud/issues/484
> Add `putfiles` command and add `parse` functions on controller.

- go/utils/config/config.go
Fix https://github.com/PaddlePaddle/cloud/issues/512
> Fix ending slash bugs.

- go/paddlectl/submit.go
- k8s/minikube/settings.py
- paddlecloud/paddlecloud/urls.py
- paddlecloud/paddlejob/cloudprovider/k8s_provider.py
- paddlecloud/paddlejob/paddle_job.py
- paddlecloud/paddlejob/specs/spec_trainingjob.py
- paddlecloud/paddlejob/views.py
Fix https://github.com/PaddlePaddle/cloud/issues/462.
>  Add "submit trainingjobs".

- .gitignore
- go/glide.lock
- go/glide.yaml
- go/hack/update-codegen.sh
- go/hack/verify-codegen.sh
- go/pkg/apis/paddlepaddle/register.go
- go/pkg/apis/paddlepaddle/v1alpha1/doc.go
- go/pkg/apis/paddlepaddle/v1alpha1/register.go
- go/pkg/apis/paddlepaddle/v1alpha1/types.go
To support CRD, I add the types for apis and they stay the same with original ones basically. The changes include:
1. change the job name `TrainingJob` to `PdJob`, because `TrainingJob` is too common and easy to conflict.
2. leave the definition of job status to @qizheng09 to implement.
plz review the codes @typhoonzero @Yancey1989
> add types for crd implementation

- docker/paddle_k8s
Job start command should not have command line arguments added by the hidden script. Use env instead.
> Fix fluid start entry
