paddlecloud/paddlecloud/settings.py

del muliti line ALLOWED_HOSTS

---

k8s/cloud_deployment.yaml
paddlecloud/Dockerfile
paddlecloud/notebook/views.py
paddlecloud/paddlecloud/urls.py
paddlecloud/requirements.txt

Add healthz and using mysql

---

doc/client_design.md

Add job api define

---

go/paddlecloud/config.go
go/paddlecloud/main.go
go/paddlecloud/submit.go
k8s/cloud_deployment.yaml
paddlecloud/notebook/views.py
paddlecloud/paddlecloud/settings.py
paddlecloud/paddlecloud/urls.py
paddlecloud/requirements.txt

Fix https://github.com/PaddlePaddle/cloud/issues/24

Init of paddlecloud client

---

docker/Dockerfile
docker/README.md
docker/build_docker.sh
docker/k8s_tools.py
docker/paddle_k8s

Build runtime docker image

---

k8s/cloud_deployment.yaml
paddlecloud/paddlecloud/settings.py

Add domain name environment

---

README.md

Add deploy on kubernetes doc

---

go/paddlecloud/get.go
paddlecloud/paddlejob/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/44

Unify jobname

---

doc/client_design.md

Fix https://github.com/PaddlePaddle/cloud/issues/53

Update client configuration sample

---

go/paddlecloud/config.go

Fix https://github.com/PaddlePaddle/cloud/issues/39

Cache tokens so we don't have to request one every time

---

doc/client_design.md
go/paddlecloud/submit.go

Post activate datacenter with paddle submit

---

docker/.gitignore
docker/Dockerfile
docker/build_docker.sh
docker/paddle_k8s

Fix https://github.com/PaddlePaddle/cloud/issues/32

Fix training job commands

---

docker/k8s_tools.py
docker/paddle_k8s

Fix invalid labels

---

README.md
k8s/cloud_deployment.yaml
paddlecloud/notebook/utils.py
paddlecloud/notebook/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/65

Fix rbac create

---

paddlecloud/notebook/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/70

Fix registry secret create

---

go/cmd/paddlecloud/.gitignore
go/cmd/paddlecloud/paddlecloud.go
go/paddlecloud/.gitignore
go/paddlecloud/config.go
go/paddlecloud/get.go
go/paddlecloud/kill.go
go/paddlecloud/logs.go
go/paddlecloud/restclient.go
go/paddlecloud/submit.go

Fix https://github.com/PaddlePaddle/cloud/issues/73

Update go structure

---

paddlecloud/paddlejob/views.py

Fix invalid mount path

---

docker/paddle_k8s
go/cmd/paddlecloud/.gitignore
go/paddlecloud/submit.go
paddlecloud/paddlejob/paddle_job.py
paddlecloud/paddlejob/views.py

Add passes paramter

---

paddlecloud/paddlejob/views.py

Fix paddlecloud logs error

---

README.md

Fix https://github.com/PaddlePaddle/cloud/issues/86

Fix doc link error

---

paddlecloud/paddlejob/paddle_job.py

Fix trainer resource

---

doc/usage_cn.md

Fix https://github.com/PaddlePaddle/cloud/issues/89

Fix sample command

---

go/paddlecloud/config.go
go/paddlecloud/get.go
go/paddlecloud/kill.go
go/paddlecloud/restclient.go
go/paddlecloud/submit.go
k8s/cloud_deployment.yaml
paddlecloud/paddlejob/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/94

Prettify output

---

paddlecloud/paddlecloud/settings.py
paddlecloud/paddlejob/paddle_job.py
paddlecloud/paddlejob/views.py

Support submit GPU jobs

---

docker/paddle_k8s
paddlecloud/paddlejob/paddle_job.py

Fix https://github.com/PaddlePaddle/cloud/issues/115

Parameter server don't use GPU

---

go/paddlecloud/config.go
go/paddlecloud/get.go
go/paddlecloud/kill.go
go/paddlecloud/logs.go
go/paddlecloud/restclient.go
go/paddlecloud/submit.go

Fix https://github.com/PaddlePaddle/cloud/issues/118

Refactor restclient

---

go/paddlecloud/restclient.go

Fix issues introduced by https://github.com/PaddlePaddle/cloud/issues/118

Fix restclient

---

go/paddlecloud/download.go
go/paddlecloud/get.go
go/paddlecloud/kill.go
go/paddlecloud/logs.go
go/paddlecloud/pfsls.go
go/paddlecloud/pfsmkdir.go
go/paddlecloud/pfsrm.go
go/paddlecloud/simplefile.go
go/paddlecloud/submit.go
go/paddlecloud/upload.go
go/utils/config.go
go/utils/restclient.go

Fix https://github.com/PaddlePaddle/cloud/issues/135

Add utils for go

---

go/utils/config.go
go/utils/restclient.go

The previous program  which gets token is a dead loop.

fix restclient bug

---

doc/usage_cn.md

Fix https://github.com/PaddlePaddle/cloud/issues/141
Add doc for jobname

Doc for jobname

---

README.md
paddlecloud/Dockerfile
paddlecloud/notebook/templates/account/email/email_confirmation_message.txt
paddlecloud/notebook/templates/account/email/email_confirmation_subject.txt
paddlecloud/requirements.txt

Fix https://github.com/PaddlePaddle/cloud/issues/103

Send registration emails

---

go/paddlecloud/simplefile.go
go/utils/config.go
go/utils/config_test.go
go/utils/restclient.go

This is part work of https://github.com/PaddlePaddle/cloud/issues/11

Add utils test

---

go/paddlecloud/simplefile.go
paddlecloud/paddlecloud/urls.py
paddlecloud/paddlejob/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/168

Simple ls for testing submit job

---

paddlecloud/paddlecloud/settings.py
paddlecloud/paddlejob/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/160

Fix storage switching

---

go/paddlecloud/get.go
go/paddlecloud/logs.go
paddlecloud/paddlejob/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/186

Fix get log api exceptions

---

docker/build_docker.sh

Install opencv-python

---

demo/fit_a_line/train.py

Save paramters

---

go/paddlecloud/get.go

Just modify quota print as flowing:
```bash
RESOURCE       LIMIT
-----          -----
Memory         100Gi
CPU            40
GPU            10
MaxParallism   40
```

Format quota print

---

docker/paddle_k8s

Fix #199 with a temporary method.

Add sleep for pserver get ready

---

paddlecloud/paddlecloud/settings.py

Fix https://github.com/PaddlePaddle/cloud/issues/228

Fix login url

---

go/paddlecloud/submit.go

check job name in client

---

k8s/cloud_deployment.yaml

fix invalid email tmpl mount path

---

docker/k8s_tools.py

Fix https://github.com/PaddlePaddle/cloud/issues/242

Fix get master ip

---

paddlecloud/notebook/utils.py
paddlecloud/paddlecloud/settings.py
paddlecloud/paddlecloud/travis_settings.py

Fix https://github.com/PaddlePaddle/cloud/issues/245

Fix notebook ingress

---

paddlecloud/paddlejob/views.py

Related: #253 
This is a temporary fix.

Fix delete master failed

---

docker/paddle_k8s

Fix https://github.com/PaddlePaddle/cloud/issues/256

Fix docker log buffer

---

go/filemanager/pfsmodules/chunkmeta.go
go/filemanager/pfsmodules/command.go
go/filemanager/pfsmodules/command_test.go
go/filemanager/pfsmodules/ls.go
go/filemanager/pfsmodules/mkdir.go
go/filemanager/pfsmodules/rm.go
go/filemanager/pfsmodules/stat.go
go/filemanager/pfsmodules/touch.go

Fix https://github.com/PaddlePaddle/cloud/issues/281

Fix ls public dataset bug

---

k8s/pfs_deployment.yaml

Fix https://github.com/PaddlePaddle/cloud/issues/281

Fix ls public data bugs

---

paddlecloud/paddlejob/paddle_job.py

Fix invalied specify trainer_count

---

doc/tutorial_cn.md
doc/usage_cn.md
go/filemanager/pfsmodules/cp.go

fix description error

---

docker/k8s_tools.py
docker/paddle_k8s

Fixed #149, the related PR #206

Max failed count

---

paddlecloud/paddlecloud/settings.py
paddlecloud/paddlejob/views.py

Configurate GPU limit in settings

---

paddlecloud/paddlejob/views.py

Fix GPU usage invalid type

---

paddlecloud/paddlejob/views.py

Fix invaild gpu usage

---

go/paddlecloud/get.go
paddlecloud/paddlejob/views.py

Fix https://github.com/PaddlePaddle/cloud/issues/295

show job terminating status

---

paddlecloud/paddlecloud/settings.py
paddlecloud/paddlejob/views.py

Fix hostpath mountpath

---

paddlecloud/paddlejob/views.py

Add env username

---

.travis.yml
go/cmd/paddlecloud/paddlecloud.go
go/paddlecloud/publish.go
paddlecloud/notebook/models.py
paddlecloud/paddlecloud/urls.py
paddlecloud/paddlejob/views.py

Resolves https://github.com/PaddlePaddle/cloud/issues/367

Rublish files for sharing

---

doc/tutorial_cn.md

Fix download link

---

doc/horizontal_autoscaling.md
paddlecloud/paddlejob/paddle_job.py

[Here](https://github.com/helinwang/cloud/blob/autoscaling/doc/horizontal_autoscaling.md) is better for review.
Fix https://github.com/PaddlePaddle/cloud/issues/379
---
This design doc can close the discussions in the issue.

 Design Doc: Horizontal Autoscaling

---

demo/fit_a_line/train.py

Add cluster RecordIO files reader

---

demo/fit_a_line/train.py

Fix save parameters

---

go/autoscaler/autoscaler.go
go/cmd/controller/controller.go
go/controller/controller.go
go/glide.lock
go/glide.yaml

Fixes: https://github.com/PaddlePaddle/cloud/issues/437

Replace logrus with log15, update glide files. Add retry limit when get trainer job errors.

---

go/paddlecloud/submit.go
paddlecloud/paddlejob/paddle_job.py
paddlecloud/paddlejob/specs/spec_trainingjob.py
paddlecloud/paddlejob/views.py

TODO:
It can not submit a thirdpartysource object with Python SDK directly, instead of request REST API.
Fixed #432

[WIP]Submit fault tolerant job in cloud server

---

go/autoscaler/autoscaler.go
go/autoscaler/autoscaler_internal_test.go

Fix https://github.com/PaddlePaddle/cloud/issues/450

Fix scale down to min

---

doc/autoscale/experiment/README.md

Thanks to the experiment result from @Yancey1989 ! Here are some tweaks.

Update autoscaling experiment design.

---

doc/autoscale/experiment/README.md

Update doe with conclusion and format tweaks

---

doc/autoscale/experiment/README.md

Fixes https://github.com/PaddlePaddle/cloud/issues/490

Polishing the experiment readme

---

doc/autoscale/README.md

Fixes https://github.com/PaddlePaddle/cloud/issues/491

Polishing the Autoscale Readme

---

paddlecloud/paddlejob/cloudprovider/k8s_provider.py

Fix volumes not defined

---

paddlecloud/requirements.txt

Fix invalid python k8s client version

---

go/filemanager/pfsmodules/touch.go

Fix https://github.com/PaddlePaddle/cloud/issues/519

add detail logs to write file

---

doc/usage_cn.md

Fix https://github.com/PaddlePaddle/cloud/issues/534

Fix demo code bug in usage doc.

---

docker/paddle_k8s

Fix https://github.com/PaddlePaddle/cloud/issues/539

support v1 split train.list

---

doc/autoscale/README.md
go/cmd/autoscaler/Dockerfile
go/controller/README.md

Fix https://github.com/PaddlePaddle/cloud/issues/541

add the process of building autoscaler controller

---

k8s/raw_job/Dockerfile
k8s/raw_job/prepare_data.py
k8s/raw_job/pserver.yaml
k8s/raw_job/train.py
k8s/raw_job/trainer.yaml

Add sample to run dist v2 job on k8s using simple yaml files.

add k8s dist train book sample

---

go/cmd/autoscaler/autoscaler.go
go/edl/autoscaler.go
go/edl/autoscaler_internal_test.go
go/edl/autoscaler_test.go
go/edl/cluster.go
go/edl/controller.go

Fix: https://github.com/PaddlePaddle/Paddle/issues/7494
Fix: https://github.com/PaddlePaddle/Paddle/issues/7493

Restructure edl package

---

README.md

Fix: https://github.com/PaddlePaddle/Paddle/issues/7498

Add develop branch build status badge

---

go/cmd/edl/edl.go

Fix: https://github.com/PaddlePaddle/cloud/issues/568

Remove buildconfig

---

docker/paddle_k8s

Fix bug introduced in https://github.com/PaddlePaddle/cloud/pull/566

Fix start up script for fluid

---

go/edl/README.md

Fix: https://github.com/PaddlePaddle/cloud/issues/588

update edl build command line

---

.tools/check_style.sh
.travis.yml
go/utils/restclient/token_test.go

Fix travis style check

---

.travis.yml
doc/edl/experiment/result/plot/plot.go
glide.lock
glide.yaml

move glide files to the top directory

---

go/updater/trainingJobUpdater.go

This pr commit the `TrainingJobUpdater` struct

commit TrainingJobUpdater struct

---

go/apis/paddlepaddle/v1/types.go
go/apis/paddlepaddle/v1/zz_generated.deepcopy.go

Use `Job` instead of `JobSpec` inside the `TrainerSpec`

fix structure of trainer

---

.copyright.hook
docker/k8s_tools.py
docker/paddle_k8s

First: add ```are_container_statuses_ready``` function to judge whether the container is ready.
Second: add configuration in pserver.yaml to check pserver listens on the server port.
```
readinessProbe:
tcpSocket:
port: 30236
initialDelaySeconds:  5
periodSeconds: 5
```

add function to judge whether the container ready

---

installation/argo/README.md
installation/k3s/README.md
installation/kubeflow/README.md

Add k3s installation guideline.

Add k3s installation guideline.

---

charts/paddlecloud/templates/serving/cluster-role-binding.yaml
charts/paddlecloud/templates/serving/cluster-role.yaml

add ClusterRole and ClusterRoleBindings for serving

[charts] fix serving ClusterRole bug

---

README-zh_CN.md
README.md
docs/design/paddlejob/design.md
docs/design/paddlejob/design_arch.md
docs/design/paddlejob/design_controller.md
docs/design/paddlejob/design_fault_tolerant.md
docs/design/sampleset/ext_benchmark.md
docs/design/sampleset/ext_benchmark_en.md
docs/design/sampleset/ext_get_start.md
docs/design/sampleset/ext_get_start_en.md
docs/design/sampleset/ext_overview.md
docs/design/sampleset/ext_overview_en.md
docs/tutorials/Installation.md
docs/tutorials/Installation_en.md
docs/tutorials/Paddlejob.md
docs/tutorials/Paddlejob_en.md
docs/tutorials/macOS_install_microk8s.md

更新了 readme、docs/tutorials、docs/design

[docs] update docs
